targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/i18n
          output_directory: lib/i18n
          output_localization_file: app_localizations.g.dart
          output_class_name: AppLocalizations
          namespaces: true
          translation_class_visibility: private
          enum_name: AppLocale
          enum_output_directory: lib/i18n
          key_case: snake
          key_map_case: snake
          string_interpolation: "dart"
          pluralization:
            auto: plural
            parameter: count