// File: apps/mobile/lib/app/router.dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import '../core/di/injection_container.dart';
import '../features/auth/presentation/pages/login_page.dart';
import '../features/auth/presentation/pages/register_page.dart';
import '../features/auth/presentation/pages/forgot_password_page.dart';
import '../features/auth/presentation/bloc/auth_bloc.dart';
import '../features/auth/presentation/bloc/auth_state.dart';
import '../features/home/presentation/pages/home_page.dart';
import '../features/brand/domain/entities/brand.dart';
import '../features/brand/presentation/pages/brand_selection_page.dart';
import '../features/brand/presentation/pages/brand_invitation_list_page.dart';
import '../features/brand/presentation/pages/create_brand_page.dart';
import '../features/brand/presentation/pages/edit_brand_page.dart';
import '../features/brand/presentation/pages/brand_stats_page.dart';
import '../features/brand/presentation/pages/brand_transfer_page.dart';

// This file will be generated by build_runner
part 'router.gr.dart';

// Global AutoRouteObserver instance for route awareness
final AutoRouteObserver routerObserver = AutoRouteObserver();

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    // Login route
    AutoRoute(
      page: LoginRoute.page,
      path: '/login',
      initial: true,
    ),
    // Register route
    AutoRoute(
      page: RegisterRoute.page,
      path: '/register',
    ),
    // Forgot password route
    AutoRoute(
      page: ForgotPasswordRoute.page,
      path: '/forgot-password',
    ),
    // Home route - protected route
    AutoRoute(
      page: HomeRoute.page,
      path: '/home',
      guards: [AuthGuard()],
    ),
    // Brand selection route
    AutoRoute(
      page: BrandSelectionRoute.page,
      path: '/brand-selection',
      guards: [AuthGuard()],
    ),
    // Brand invitation list route
    AutoRoute(
      page: BrandInvitationListRoute.page,
      path: '/brand-invitation-list',
      guards: [AuthGuard()],
    ),
    // Create brand route
    AutoRoute(
      page: CreateBrandRoute.page,
      path: '/create-brand',
      guards: [AuthGuard()],
    ),
    // Edit brand route
    AutoRoute(
      page: EditBrandRoute.page,
      path: '/edit-brand/:brandId',
      guards: [AuthGuard()],
    ),
    // Brand stats route
    AutoRoute(
      page: BrandStatsRoute.page,
      path: '/brand-stats',
      guards: [AuthGuard()],
    ),
    // Brand transfer route
    AutoRoute(
      page: BrandTransferRoute.page,
      path: '/brand-transfer',
      guards: [AuthGuard()],
    ),
  ];
}

/// Auth guard to protect routes
class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final authBloc = getIt<AuthBloc>();
    final isAuthenticated = authBloc.state is AuthSuccess;

    if (isAuthenticated) {
      resolver.next(true);
    } else {
      router.pushNamed('/login');
      resolver.next(false);
    }
  }
}