// File: apps/mobile/lib/app/router.dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../core/di/injection_container.dart';
import '../features/auth/presentation/pages/responsive_login_page.dart';
import '../features/auth/presentation/pages/login_page.dart';
import '../features/auth/presentation/pages/register_page.dart';
import '../features/auth/presentation/bloc/auth_bloc.dart';
import '../features/auth/presentation/bloc/auth_state.dart';
import '../features/home/presentation/pages/home_page.dart';

// This file will be generated by build_runner
part 'router.gr.dart';

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    // Login route - menggunakan ResponsiveLoginPage
    AutoRoute(
      page: ResponsiveLoginRoute.page, // Pastikan ini ResponsiveLoginRoute
      path: '/login',
      initial: true,
    ),
    // Register route
    AutoRoute(
      page: RegisterRoute.page,
      path: '/register',
    ),
    // Home route - protected route
    AutoRoute(
      page: HomeRoute.page,
      path: '/home',
      guards: [AuthGuard()],
    ),
  ];
}

/// Auth guard to protect routes
class AuthGuard extends AutoRouteGuard {
  @override
  void onNavigation(NavigationResolver resolver, StackRouter router) {
    final authBloc = getIt<AuthBloc>();
    final isAuthenticated = authBloc.state is AuthSuccess;

    if (isAuthenticated) {
      resolver.next(true);
    } else {
      router.pushNamed('/login');
      resolver.next(false);
    }
  }
}