// Mocks generated by Mockito 5.4.5 from annotations
// in usago/test/features/auth/helpers/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:usago/core/errors/failure.dart' as _i6;
import 'package:usago/core/network/dio_client.dart' as _i13;
import 'package:usago/core/services/secure_storage_service.dart' as _i12;
import 'package:usago/features/auth/data/datasources/auth_local_datasource.dart'
    as _i11;
import 'package:usago/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i9;
import 'package:usago/features/auth/data/models/user_model.dart' as _i10;
import 'package:usago/features/auth/domain/entities/user.dart' as _i7;
import 'package:usago/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.User>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i7.User>>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.User>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.User>> register({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.User>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i7.User>>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.User>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.User?>> checkAuthStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAuthStatus,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.User?>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i7.User?>>(
          this,
          Invocation.method(
            #checkAuthStatus,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.User?>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.User>> refreshToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.User>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i7.User>>(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.User>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> forgotPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #token: token,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #token: token,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.User>> updateProfile({
    String? name,
    String? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.User>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i7.User>>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #name: name,
              #profilePicture: profilePicture,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i7.User>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> verifyEmail(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #verifyEmail,
            [token],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resendVerificationEmail() =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationEmail,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #resendVerificationEmail,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i9.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i10.UserModel>>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>> register({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i10.UserModel>>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>> refreshToken() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i10.UserModel>>(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> forgotPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #token: token,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #token: token,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>> updateProfile({
    String? name,
    String? profilePicture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #profilePicture: profilePicture,
          },
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, _i10.UserModel>>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #name: name,
              #profilePicture: profilePicture,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i10.UserModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> verifyEmail(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #verifyEmail,
            [token],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resendVerificationEmail() =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationEmail,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #resendVerificationEmail,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
            _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, void>>);
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i11.AuthLocalDatasource {
  MockAuthLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUser(_i10.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i10.UserModel?> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i4.Future<_i10.UserModel?>.value(),
      ) as _i4.Future<_i10.UserModel?>);

  @override
  _i4.Future<void> clearUser() => (super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSessionData(Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionData,
          [sessionData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getSessionData() => (super.noSuchMethod(
        Invocation.method(
          #getSessionData,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearSessionData() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<DateTime?> getLastLoginTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastLoginTime,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> saveLastLoginTime(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #saveLastLoginTime,
          [time],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllAuthData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i12.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSecureStorageAvailable => (super.noSuchMethod(
        Invocation.getter(#isSecureStorageAvailable),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> saveSecureData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSecureData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSecureData,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> removeSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeSecureData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveNonSecureData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNonSecureData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getNonSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getNonSecureData,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> removeNonSecureData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeNonSecureData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllSecureData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllSecureData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllNonSecureData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllNonSecureData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> getStorageInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStorageInfo,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void logPlatformInfo() => super.noSuchMethod(
        Invocation.method(
          #logPlatformInfo,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isFeatureSupported(String? feature) => (super.noSuchMethod(
        Invocation.method(
          #isFeatureSupported,
          [feature],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserData(String? userData) => (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [userData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSessionData(Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSessionData,
          [sessionData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getSessionData() => (super.noSuchMethod(
        Invocation.method(
          #getSessionData,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearSessionData() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllAuthData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i13.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<Map<String, dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> postWithHeaders(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postWithHeaders,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #postWithHeaders,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
